//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BadEcho.QuickActions.SystemSettings.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BadEcho.QuickActions.SystemSettings.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the primary display to the next monitor to the right, according to the arrangement defined in the user&apos;s display settings. If the current primary display device is already the rightmost monitor, then the leftmost monitor will be made the primary display device..
        /// </summary>
        internal static string ChangePrimaryDisplayDescription {
            get {
                return ResourceManager.GetString("ChangePrimaryDisplayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to make the monitor &apos;{0}&apos; the primary display device..
        /// </summary>
        internal static string ChangePrimaryDisplayFailed {
            get {
                return ResourceManager.GetString("ChangePrimaryDisplayFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Primary Display.
        /// </summary>
        internal static string ChangePrimaryDisplayName {
            get {
                return ResourceManager.GetString("ChangePrimaryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to locate a default input audio device..
        /// </summary>
        internal static string NoMicrophoneFoundToToggle {
            get {
                return ResourceManager.GetString("NoMicrophoneFoundToToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles the mute state of the system&apos;s default input audio device..
        /// </summary>
        internal static string ToggleMicrophoneMuteDescription {
            get {
                return ResourceManager.GetString("ToggleMicrophoneMuteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to toggle the mute state of the default input audio device..
        /// </summary>
        internal static string ToggleMicrophoneMuteFailed {
            get {
                return ResourceManager.GetString("ToggleMicrophoneMuteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Microphone Mute.
        /// </summary>
        internal static string ToggleMicrophoneMuteName {
            get {
                return ResourceManager.GetString("ToggleMicrophoneMuteName", resourceCulture);
            }
        }
    }
}
